kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
    - go test -v .
    - go build .

- name: build
  image: golang
  commands:
    - go build .

- name: benchmark
  image: golang
  commands:
    - go test -v . -bench . -cpu=2,4,8 -run=noExist -count=5

