kind: pipeline
type: docker
name: default

steps:

- name: getVersion
  image: ubuntu
  commands:
    - echo "TODO"

- name: test-module
  image: golang
  commands:
    - go test -v .

- name: generate-benchmark-report
  image: golang
  commands:
    - echo "" >> benchmark.md
    - |
      echo "## Version: $VESRION" >> benchmark.md
    - go test -v . -bench . -cpu=2 -run=noExist -count=1 | tee -a benchmark.md
  when:
    branch:
      - main

- name: generate-changelog-report
  image: alpine/git
  commands:
    - echo "" >> CHANGELOG.md
    - |
      echo "## Version: $VESRION" >> CHANGELOG.md
    - git log $(git describe --tags --abbrev=0)..HEAD --oneline | tee -a CHANGELOG.md
  when:
    branch:
      - main

- name: publish-reports
  image: alpine/git
  commands:
    - git add CHANGELOG.md benchmark.md
    - |
      git commit -m 'ci: Uploading Reports [CI SKIP]'
    - git push
  when:
    branch:
      -main

- name: tagVersion
  image: alpine/git
  commands:
    - echo "TODO"

    
trigger:
  event:
    - push
