kind: pipeline
type: docker
name: benchmarks

steps:
- name: git-fetch
  image: alpine/git
  commands:
    - git fetch --tags

- name: test-module
  image: golang
  commands:
    - go build .

- name: generate-benchmark-report
  image: golang
  commands:
    - VERSION=`cat .version`
    - echo "" >> benchmark.md
    - |
      echo "## Version: $VESRION" >> benchmark.md
    - go test -v . -bench . -cpu=2 -run=noExist -count=1 | tee -a benchmark.md

- name: go-publish-benchmark-report
  image: jmccann/drone-github-comment:1
  environment:
    GH_TOKEN:
      from_secret: github_token
  commands:
    - MESSAGE=`cat .benchmark.md`
    - |
      /bin/drone-github-comment --repo-owner annonch --repo-name simian-go
      --pull-request  --api-key $GH_TOKEN --message $MESSAGE

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: default

steps:
- name: git-fetch
  image: alpine/git
  commands:
    - git fetch --tags

- name: test-module
  image: golang
  commands:
    - go test -v .

- name: go-semantic-release-install
  image: alpine/curl
  commands:
    - wget https://github.com/Nightapes/go-semantic-release/releases/download/v2.0.1/go-semantic-release.linux_x86_64.zip
    - unzip go-semantic-release.linux_x86_64.zip
    - ls -al .
  when:
    branch:
      - main

- name: go-semantic-release
  image: golang
  environment:
    CI: true
    GH_TOKEN:
      from_secret: github-token
    GITHUB_TOKEN:
      from_secret: github-token
  commands:
    - ./go-semantic-release.linux_x86_64 help --loglevel debug
    - ./go-semantic-release.linux_x86_64 next --checks --loglevel debug
    - ./go-semantic-release.linux_x86_64 release --loglevel debug
  when:
    branch:
      - main

# - name: generate_changelog-report
#   image: naorlivne/drone-github-changelog-generator
#   settings:
#     github_user: ${DRONE_REPO_NAMESPACE}
#     github_project: ${DRONE_REPO_NAME}
#     output_path: CHANGELOG.md
#   when:
#     branch:
#       - main

# - name: publish-reports
#   image: alpine/git
#   commands:
#     - git add CHANGELOG.md benchmark.md
#     # - |
#     #   git commit -m
#     # - git push --set-upstream origin main
#     # - git push
#   when:
#     branch:
#       - main

# - name: push commit
#   image: appleboy/drone-git-push
#   settings:
#     remote_name: origin
#     branch: main
#     local_ref: main
#     author_name: drone-nc
#     commit: true
#     commit_message: |
#                     ci: Uploading Reports [CI SKIP]
#   when:
#     branch:
#       - main

# - name: tagVersion
#   image: alpine/git
#   commands:
#     - echo "TODO"


  
trigger:
  event:
    - push


  
